### ISSUE TITLE
Expanded Canon

### ISSUE THREAD

**Issue by aletheist** [davisd/python-scriptures#10]
Would you be willing to accept a merge request that adds the Greek Old Testament ([Septuagint/LXX](https://en.wikipedia.org/wiki/Septuagint)) books?

This would require a special case for the Psalms since the numbering is different in the LXX, Daniel because there is additional text, the addition of several books (e.g. 1-4 Maccabees), among other changes.

**Comment by strawhead** [comment]
Wouldn't Psalms and Daniel be a matter of simply recognizing additional chapters (and verses) as valid references? The Psalms numbering doesn't map, but this library doesn't really deal with which text the numbers refer to--just recognizes the references and pulls them out, right? For that matter, the other book names should be just simple adaptations of existing code: e.g., 1-4 Maccabees would look like 1-3 John. This seems immanently doable--enough that I'm tempted to try.

I'm no LXX scholar. Is there anything I'm missing?

P.S., thanks a lot for the library, @davisd, it saved me a ton of time over several years.

**Comment by davisd** [comment]
@strawhead - Thank you for that!  I'm happy to hear that this tool has helped you.  I'm encouraged by some of the recent discussion here.  To answer your question about the numbering- the library does provide for validating scripture references based upon valid chapter/verse references.

@JeffMelton - Thank you for the work you've done in your fork.  I want to recognize you for that- you've taken the time to put together regex for books, etc.  I want to incorporate some of your work upstream.  I'd like to talk to you about the best way to do that within the framework discussed below.  I could copy/paste some of your code, but I'd much rather see your face on the commits.

I think that with the issue that @aletheist has opened regarding the expansion of books, along with some of the work that @JeffMelton has done on his fork- I see the following key issue to address:

* Different people and use-cases need different text configurations

python-scriptures provides a very simple and effective interface to validating, extracting and normalizing biblical scripture references from blocks of text.  Right now, these references must  be in-line with the canonical books of the Old and New Testaments.

That configuration works great for my original intended use, which is on the www.centralbaptistfwb.com/sermons/ sermon archive to identify and highlight scriptures- and then link them to the appropriate books in the www.centralbaptistfwb.com/bible/ section.

If we were to incorporate @aletheist PR to change chapter/verse counts in the ot and nt dicts (for Psalms, Daniel), that would break my (and others I'm guessing) use-case.  If we were to incorporate Apocryphical/Deuterocanonical texts, that would also break my use-case, as now I may get scriptures highlighted/linking that I cannot link to (as the /bible/ section of the website only has the canonical texts).

And so, I am going to work to:

* Provide a simple method/interface for specifying text configurations.

I want to secondarily:

* Make extending the package's text configurations (Book regex, chapter/verse counts), and recognizing contributions very simple/straightforward
* Not break the current API
* Give a preferential default to the canonical text of the OT and NT.  In doing so, I will accomplish the goal of not breaking the API.

I intend to work on this today and post a new branch.  I will add some apocryphal texts as a starting point – and to demo.

I'm starting these changes right away and would love to hear any feedback on this and on the branch (when pushed).

Thanks again everyone,
-David

**Comment by strawhead** [comment]
@davisd Things just got ecumenical! Your use case was identical to mine, so I can't argue with your planned defaults. Just a note, because I recently learned this: the *Septuagint references aren't quite equal to the Roman Catholic OT + Deuterocanonical books.* In case you need them, here is a list of the RC OT+D books:

* Genesis
* Exodus
* Leviticus
* Numbers
* Deuteronomy
* Joshua
* Judges
* Ruth
* 1 Samuel
* 2 Samuel
* 1 Kings
* 2 Kings
* 1 Chronicles
* 2 Chronicles
* Ezra
* Nehemiah
* Tobit
* Judith
* Esther
* 1 Maccabees
* 2 Maccabees
* Job
* Psalms
* Proverbs
* Ecclesiastes
* Song of Solomon
* Wisdom
* Sirach
* Isaiah
* Jeremiah
* Lamentations
* Baruch
* Ezekiel
* Daniel
* Hosea
* Joel
* Amos
* Obadiah
* Jonah
* Micah
* Nahum
* Habakkuk
* Zephaniah
* Haggai
* Zechariah
* Malachi

**Comment by JeffMelton** [comment]
@davisd I'm glad you're able to give this some love, and I'd be glad to help how I can. I don't get a ton of time to play around with stuff like this, and my skill level might generously be described as "hobbyist"... but when you figure out where you want it to go and how you'd like my contributions to be presented, let me know. I'll do my best. :smile:

**Comment by davisd** [comment]
Ok, I came up with this as a potential solution (pushed to v3dev branch).

## Defining a new "Text"

To define a new Text, you create a class that inherits scriptures.texts.base.Text and define the "books" class attribute.

So for example-
```
>>> from __future__ import unicode_literals
>>> from scriptures.texts.base import Text
>>> class MyText(Text):
>>>     books=[
>>>         ('Book 1', 'Bk1', 'Book(?:\s)?1|bk(?:\s)?1', [2,4,6]),
>>>         ('Book 2', 'Bk2', 'Book(?:\s)?2|bk(?:\s)?2', [7,8,9])
>>>     ]
```
## Using your new Text

Once your Text class is defined- you can do:
```
>>> my_text=MyText()
>>> my_text.extract('Lets see if it finds bk1 2:2-4 and Book 2 3:9')
[(u'Book 1', 2, 2, 2, 4), (u'Book 2', 3, 9, 3, 9)]
```
All of the same helper functions are available- but now they are accessed from the Text instance
* get_book
* extract
* is_valid_reference
* reference_to_string
* normalize_reference

## Regex on Instances

Your instance also has some helper regular expression instance variables
* book_re - will match books
* scripture_re - will match scripture patterns

So, you can do:
```
>>> my_text.scripture_re.findall('Hi there- looking for Bk1 1 and Book 2 1:1-2')
[(u'Bk1', u'1', u'', u'', u''), (u'Book 2', u'1', u'1', u'', u'2')]
```

## Library-provided texts

Under the scriptures/texts/ folder, there are a few files-

* base.py
* deuterocanon.py
* kjv1611.py
* protestant.py

base.py defines the Text class that new texts will inherit.  Each of the other modules contains a class that inherits the Text class.  The subclasses simply define the "books" class attribute.

Please take a look at these to see how to define new Texts.

As we need more texts, or variations of texts, we can simply create new modules under this /texts/ folder.

## Making your own Texts

If you have a specific Text for your project that would not make sense to contribute to this library, you can define your own Text class and keep it to yourself.  No need to fork the project just for a new text! :)

## API Defaults

To keep the previous API in-tact, the library declares a ProtestantCanon Text instance- so if you’re using the library per the current documentation w/2.x API (scriptures.extract(...), etc)- nothing changes.

Extending texts is trivial now- my explanation here may over-complicate it!  Please tell me what you guys think about this approach.

-David

**Comment by davisd** [comment]
@JeffMelton - Thank you! For starters- I'd like to give you attribution for your work on the Deuterocanon regex. Would you mind submitting a pull request that implements those books in the /scriptures/texts/deuterocanon.py module (on the v3dev branch) - per your 'deut' dict in bible_re.py ?  It should be nearly a copy-paste.

I may separate out the III and IV Maccabees to another deuterocanon2.py -  I don't think those are included in the KJV 1611 (which currently pulls in deuterocanon.py).  Then we can then associate both of those with new texts- maybe "RomanCatholicOrthodox" and "Septuagint"?  I'll need to do some research on that- we want to make sure that we get the texts right. Thank you @strawhead for pointing out some resources and emphasizing the numbering issues.

@aletheist  - I think this new setup will allow us to implement a Septuagint pretty quickly.  Would you like to contribute to that module in this new framework?

-David

**Comment by aletheist** [comment]
I would be willing to contribute under this new framework.

Rather than a `deuterocanon2.py` we will probably need a `septuagint.py`. This is because the LXX is not a simple superset of the 66 book canon or the Deuterocanon. In a few books, the LXX inserts verses to Daniel directly whereas denominations that give primacy to the Masoretic text but still use the Deuterocanon usually have that as an appendix. The Psalm chapter/verse numbering doesn't match up. Proverbs is just a nightmare; the LXX version [might as well be a different book from the Masoretic](http://ccat.sas.upenn.edu/nets/edition/25-proverbs-nets.pdf).

Using the strategy you outlined, I should be able to create an `septuagint.py` module that leaves books that are identical the same, so I will only need override books with different versification/length, and add other books (III, IV Maccabees, etc) correct?

**Comment by davisd** [comment]
It's not too much work, and I think you're right.  If we did that, it would really simplify overrides.

**Comment by JeffMelton** [comment]
@davisd I'm going to pull in @mlv here, because he's actually who contributed that code to my fork. I think the deuterocanonical texts suit his use case better, and he's a *much* more experienced programmer than I am. If he's interested, he'll submit cleaner code than I will (and he may be able to get to it more quickly than I can).

If he can't, or isn't interested, I'll see what I can muddle through with.

**Comment by mlv** [comment]
My first thought when I read @davisd's v3dev post/idea was that I like it. Have all the books in a basic version, then add or change them as needed. I also agree that we need a septuagint.py. TBH, I haven't looked at this in a while and forgot that it wasn't a dictionary. But yes, it needs to be one, so that we can change or delete specific books as needed.

I don't think changing it to a dictionary is too hard. Changing the data itself is easy:
s/(\([^,]*\), (/

And most of the code changes are just adding .values() to self.books and tweaking indices.

**Comment by mlv** [comment]
In thinking more about it, I have a better idea of how to do the dictionary. Rather than:

```
books={
    'Book 1': ('Bk1', 'Book(?:\s)?1|bk(?:\s)?1', [2,4,6]),
    'Book 2': ('Bk2', 'Book(?:\s)?2|bk(?:\s)?2', [7,8,9])
}
```

keep the book name inside the dict, as in:

```
books={
    'Book 1': ('Book 1', 'Bk1', 'Book(?:\s)?1|bk(?:\s)?1', [2,4,6]),
    'Book 2': ('Book 2', 'Bk2', 'Book(?:\s)?2|bk(?:\s)?2', [7,8,9])
}
```
Disadvantage of this is that it breaks the duplication of information rule. But it means that all the existing code that accesses the information as a tuple works without changing. You just iterate through books.values() instead of books and it all works the same way.

**Comment by mlv** [comment]
@aletheist if you upload (with approval, etc), the LXX version, I'll convert the code to a dictionary.

**Comment by aletheist** [comment]
There are two publicly available LXXs:

[Brenton](http://www.ecmarsh.com/lxx/) and [New English Translation of the Septuagint](http://ccat.sas.upenn.edu/nets/#pub).

**Comment by davisd** [comment]
I just updated the v3dev branch to treat "books" as dictionaries.

If you look under scriptures/texts, you will see several python modules implementing "Texts"

![protestant.py](https://github.com/davisd/python-scriptures/blob/v3dev/scriptures/texts/protestant.py)- contains the Protestant Bible data as it was, but now converted to a dictionary.

![deuterocanon.py](https://github.com/davisd/python-scriptures/blob/v3dev/scriptures/texts/deuterocanon.py) - contains a basic Deuteronomical Canon.  Tobit is the only book implemented- the remaining books are listed as TODOs.

![kjv1611.py](https://github.com/davisd/python-scriptures/blob/v3dev/scriptures/texts/kjv1611.py) - is the KJV 1611 - as you can see from that file, it simply combines the ProtestantCanon with the Deuterocanon and then adds books.

@mlv - if you would like to be recognized for your Regex efforts in this- would you mind submitting a pull request to implement the deuterocanon.py file using the new v3dev branch, under scriptures/texts ?

Once that is straight- the kjv1611 should be fully implemented.

We can then create a septuagint.py, which (I think) will implement the ProtestantCanon and the DeuteroCanon- and then will override the key/values for the various books (to change verse counts, etc).

@mlv- I like the idea of using the book's primary abbreviation instead of the full Book Name as the dict key, as it is easier to reference/less verbose. You're right, there is duplicate information, but it's not much, and I think the end result is very clean.

What are you guys thoughts?

**Comment by mlv** [comment]
@davisd Pull request submitted.

**Comment by davisd** [comment]
Thank you for that @mlv - it is much appreciated.  I merged your commits and made some updates.  I have been using the Crosswire OSIS abbreviations page for reference on abbreviations- https://crosswire.org/wiki/OSIS_Book_Abbreviations

We may have an issue with the "Esther (Greek)" / "Additions to Esther" / "Rest of Esther" in relation to the Deuterocanon and the KJV1611.  I might be getting these mixed up/crossed.  I will try to research this out a bit more tonight.  If you have some insight/links resources, would you mind posting?

Thanks again.

**Comment by davisd** [comment]
For the sake of getting this work posted before the new year, I went ahead and tagged v3.0.0 at 7c19af4.

This release implements and documents the new method of defining/extending Texts.

Thanks to everyone involved for helping get this posted (@aletheist, @strawhead, @JeffMelton, @mlv)!  If I get pull requests for additional texts (Septuagint, Vulgate, etc)- I will review, pull, maybe edit, and certainly post!

I'm going to close this ticket.

Happy New Year!
-David
